language: java
jdk: oraclejdk11

install: true

script: - mvn install

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - musin.idris@gmail.com
    on_failure: always
    on_success: change